micronaut:
  application:
    name: casaDoCodigo


datasources:
  default:
    url: jdbc:postgresql://localhost:5432/cdc
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
    dialect: POSTGRES

jpa.default.properties.hibernate.hbm2ddl.auto: update



